---
name: CI
on:
  puch:
    branches:
      - main
jobs:
  job1:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Run a one-line script
  job2:
    dev:
      name: Development
      steps:
        - name: Run the developer
  job3:
    test:
      needs: job2
      name: Test
      steps:
        - name: Testing the application

