name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  dev:
    name: Development
    runs-on: ubuntu-latest
    steps:
      - name: Run the developer
        run: echo "Running development steps..."

  build:
    name: Build
    needs: [ dev ]
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy on Cloud
        run: echo "Building and deploying..."

  test:
    name: Test
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Testing the application
        run: echo "Running tests..."
